#!/usr/bin/env python3
"""mkplugin.py <qemu source dir> <out.c>: writes fnprof.c, QEMU's contrib/plugins/hotblocks.c changed to write every
block (start address, instructions, executions) to a file every 10 s and at exit. The result is QEMU code
(GPL-2.0-or-later), so it is generated here rather than kept in this repository."""
import sys
src = open(sys.argv[1] + "/contrib/plugins/hotblocks.c").read()
start = src.index('static void plugin_exit'); end = src.index('static void plugin_init')
dump = r'''static char out_path[512] = "/tmp/fnprof.txt";
static void dump_one(gpointer key, gpointer value, gpointer user_data)
{
    ExecCount *rec = value;
    uint64_t n = qemu_plugin_u64_sum(qemu_plugin_scoreboard_u64(rec->exec_count));
    if (n) fprintf((FILE *)user_data, "%" PRIx64 " %lu %" PRIu64 "\n", rec->start_addr, rec->insns, n);
}
static void dump(void)
{
    char tmp[600]; snprintf(tmp, sizeof tmp, "%s.new", out_path);
    FILE *f = fopen(tmp, "w"); if (!f) return;
    g_mutex_lock(&lock);
    g_hash_table_foreach(hotblocks, dump_one, f);
    g_mutex_unlock(&lock);
    fclose(f); rename(tmp, out_path);
}
static gpointer dumper(gpointer d) { for (;;) { g_usleep(10 * G_USEC_PER_SEC); dump(); } return NULL; }
static void plugin_exit(qemu_plugin_id_t id, void *p) { dump(); }

'''
src = src[:start] + dump + src[end:]
src = src.replace('        } else {\n            fprintf(stderr, "option parsing failed: %s\\n", opt);',
                  '        } else if (g_strcmp0(tokens[0], "out") == 0 && tokens[1]) {\n'
                  '            snprintf(out_path, sizeof out_path, "%s", tokens[1]);\n'
                  '        } else {\n            fprintf(stderr, "option parsing failed: %s\\n", opt);')
src = src.replace('    plugin_init();\n', '    plugin_init();\n    g_thread_new("fnprof-dump", dumper, NULL);\n')
open(sys.argv[2], "w").write("/* fnprof: generated by SuperDrastic's tools/sim/mkplugin.py from QEMU's contrib/plugins/hotblocks.c */\n" + src)
