/* res2.c: the 2x bin resolve without fog or edge marking (DraStic's video_3d_resolve_bin_asm_4x, spec/resolve.c's
 * spec_video_3d_resolve_bin_4x) in NEON, fused with the compositor's visibility table (comp.c's comp_bin()).
 *
 * The resolve: output line y = colour line y & 0x1fffffff, the 256 even pixels at +0, the 256 odd ones at +0x400.
 * DraStic's loop is the minimal one (ld2.4s, and, st1 per 8 pixels) but issues its four ld2 back to back and each
 * `and` right after its load: llvm-mca's A55 model gives it 68 cycles per 32 pixels (ld2.4s occupies the load unit 4
 * cycles, latency 7), 0.41 M a frame. comp_bin() then reads the block back (ld4.16b, 8 load cycles per 16 pixels) for
 * the 64 half-rows' visibility entries (render_scanline_set_3d_visibility's bitmap and flag, compvis.h), 0.23 M.
 *
 * Here both come from the same registers, one line (two half-rows) at a time. Per 32 pixels of a line:
 *   ldr q x8, bic x8  the pixels masked (bic #0xe0 << 24 = & 0x1fffffff);
 *   uzp1/uzp2 x8, stp x4   the even pixels E0..E3 (16) and the odd O0..O3 to the two half-rows, DraStic's bytes;
 *   uzp2.8h x2 + uzp2.16b   byte 3 of the 16 masked even pixels in one vector: their 5-bit alphas a (likewise odd);
 *   cmtst m = (a != 0), m & {1, 2, .., 128, 1, .., 128}: each pixel's bit weight in its bitmap byte; the addp tree
 *               of compvis.h folds 16 such vectors into the half-row's 32 bitmap bytes (level 1 per 64 pixels of the
 *               line, level 2 per 128, level 3 per 256 = bitmap bytes 0..15, then 16..31);
 *   bic(m, a) = ~a where a != 0, OR-accumulated: its low 5 bits are 31 - a there (a <= 31 after the mask), non-zero
 *               exactly when 0 < a < 31, compvis.h's "translucent" condition (it uses umin(a, a ^ 31)).
 * The flag is then 2 if some pixel is translucent, else 0x10 if some bitmap byte is non-zero, else 0: the same 32
 * bytes and value as compvis.h on the written half-row (spec/composite.c's port for any input; t_resolve.c checks
 * these against DraStic's resolve and the port). Without a table (RAST_COMP < 2, or the output frame not one of
 * the two the table follows) only the resolve runs. res2_vis_bin() computes the same entries from a block written
 * by DraStic's fog and edge-marking resolves (comp_bin(); also the 3x pipeline's). */
#include <arm_neon.h>
#include <stdint.h>
#include "res2.h"

/* 32 pixels of a colour line: masked to the even (e) and odd (o) half-rows (the path without a table) */
static inline __attribute__((always_inline)) void px32(const uint32_t *s, uint32_t *e, uint32_t *o, uint32x4_t m) {
    uint32x4x2_t a = vld2q_u32(s), b = vld2q_u32(s + 8), c = vld2q_u32(s + 16), d = vld2q_u32(s + 24);
    vst1q_u32(e, vandq_u32(a.val[0], m)); vst1q_u32(e + 4, vandq_u32(b.val[0], m));
    vst1q_u32(e + 8, vandq_u32(c.val[0], m)); vst1q_u32(e + 12, vandq_u32(d.val[0], m));
    vst1q_u32(o, vandq_u32(a.val[1], m)); vst1q_u32(o + 4, vandq_u32(b.val[1], m));
    vst1q_u32(o + 8, vandq_u32(c.val[1], m)); vst1q_u32(o + 12, vandq_u32(d.val[1], m));
}

/* The fused line is res2_line.S, generated by res2gen.py: the line's dependence graph list-scheduled for llvm-mca's
 * A55 model (ldr q + uzp instead of ld2, whose 7-cycle latency stalls every later instruction of an in-order
 * retirement; see res2gen.py). 707 modeled cycles a line (a hand-written ld2 version: 983; DraStic's resolve alone
 * 1088, then comp_bin()'s two half-rows). It stores the line's two half-rows and the bitmaps of both table entries
 * (b, b + 32) and returns the translucency accumulators' low 5 bits, moved to the top, even | odd << 8 (non-zero:
 * some 0 < a < 31). */
uint32_t res2_line_asm(const uint32_t *s, uint32_t *e, uint32_t *o, uint8_t *b, const uint8_t *wts);
/* the same bitmaps of an output line already written (comp_bin() after DraStic's fog and edge-marking resolves):
 * ldr q + uzp2 for the alphas instead of compvis.h's ld4 (latency 11), umin(a, a ^ 31) for the translucency as
 * compvis.h (bits 5-7 of the alpha byte may be set there); 468 modeled cycles a line against compvis.h's ~610 */
uint32_t comp_vis_line_asm(const uint32_t *line, uint8_t *b, const uint8_t *wts);

static const uint8_t w8[16] = { 1, 2, 4, 8, 16, 32, 64, 128, 1, 2, 4, 8, 16, 32, 64, 128 };

/* compvis.h's return value for a half-row's bitmap: 2 if some pixel is translucent (te), else 0x10 if some is visible */
static inline uint8_t vis_flag(const uint8_t *bits, uint32_t te) {
    if (te) return 2;
    return vmaxvq_u8(vorrq_u8(vld1q_u8(bits), vld1q_u8(bits + 16))) ? 0x10 : 0;
}

void res2_resolve(uint8_t *out, const uint32_t *col, uint8_t (*bits)[32], uint8_t *flags) {
    if (!bits) {
        const uint32x4_t m = vdupq_n_u32(0x1fffffff);
        for (int y = 0; y < 32; y++) {
            const uint32_t *s = col + y * 512;
            uint32_t *e = (uint32_t *)(out + y * 0x800), *o = e + 256;
            for (int x = 0; x < 512; x += 32, s += 32, e += 16, o += 16) px32(s, e, o, m);
        }
        return;
    }
    for (int y = 0; y < 32; y++) {
        uint32_t *e = (uint32_t *)(out + y * 0x800);
        uint32_t t = res2_line_asm(col + y * 512, e, e + 256, bits[2 * y], w8);
        flags[2 * y] = vis_flag(bits[2 * y], t & 0xff);
        flags[2 * y + 1] = vis_flag(bits[2 * y + 1], t >> 8);
    }
}

void res2_vis_bin(const uint8_t *blk, uint8_t (*bits)[32], uint8_t *flags) {
    for (int y = 0; y < 32; y++) {
        uint32_t t = comp_vis_line_asm((const uint32_t *)(blk + y * 0x800), bits[2 * y], w8);
        flags[2 * y] = vis_flag(bits[2 * y], t & 0xff);
        flags[2 * y + 1] = vis_flag(bits[2 * y + 1], t >> 8);
    }
}
