#!/usr/bin/env python3
"""Build dsstress .nds ROMs: a tunable 3D stress load for DraStic (see main9.c).

    build.py                      -> out/dsstress-ramp.nds, out/dsstress-L1..L10.nds, out/dsswap.nds
Needs clang + ld.lld (targets armv5te for the ARM9; the ARM7 is a 4-byte halt stub).
Header layout mirrors the minimal ROM DraStic is known to boot: ARM9 at 0x8000, no logo.
"""
import math, os, struct, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
os.makedirs(OUT, exist_ok=True)

def fx(v): return int(round(v * 4096))

# tables.h: sine table (4.12) and the perspective projection (20.12, libnds glFrustum order)
sintab = [fx(math.sin(i * 2 * math.pi / 256)) for i in range(256)]
fovy, aspect, near, far = 60.0, 256 / 192, 0.5, 40.0
top = near * math.tan(math.radians(fovy / 2)); right = top * aspect
proj = [fx(2 * near / (2 * right)), 0, 0, 0,
        0, fx(2 * near / (2 * top)), 0, 0,
        0, 0, fx(-(far + near) / (far - near)), fx(-1),
        0, 0, fx(-2 * far * near / (far - near)), 0]
with open(os.path.join(HERE, "tables.h"), "w") as f:
    f.write("/* generated by build.py */\n")
    f.write("static const short sintab[256] = {%s};\n" % ",".join(map(str, sintab)))
    f.write("static const int proj[16] = {%s};\n" % ",".join(map(str, proj)))

LD = """ENTRY(_start)
SECTIONS {
  . = 0x02000000;
  .text : { *(.text.start) *(.text*) *(.rodata*) }
  .data : { *(.data*) }
  . = ALIGN(4);
  __bss_start = .;
  .bss : { *(.bss*) *(COMMON) }
  . = ALIGN(4);
  __bss_end = .;
  /DISCARD/ : { *(.ARM.exidx*) *(.ARM.extab*) }
}
"""
with open(os.path.join(OUT, "ld9.ld"), "w") as f: f.write(LD)

T = ["--target=armv5te-none-eabi", "-marm", "-mfloat-abi=soft"]
def run(cmd): subprocess.run(cmd, check=True, cwd=HERE)
run(["clang", *T, "-O2", "-fno-unwind-tables", "-fno-asynchronous-unwind-tables", "-ffreestanding", "-fno-builtin", "-nostdlib", "-Wall", "-c", "main9.c", "-o", "out/main9.o"])
run(["clang", *T, "-c", "crt9.s", "-o", "out/crt9.o"])
run(["ld.lld", "-T", "out/ld9.ld", "out/crt9.o", "out/main9.o", "-o", "out/arm9.elf"])
run(["llvm-objcopy", "-O", "binary", "out/arm9.elf", "out/arm9.bin"])
arm9 = bytearray(open(os.path.join(OUT, "arm9.bin"), "rb").read())
assert arm9[4:8] == b"STRS", "config block not at offset 4"
# ARM7 stub: HALTCNT <- 0x80 in a loop (ldr/strb/b with the address in a literal)
arm7 = struct.pack("<5I", 0xE59F0008, 0xE3A01080, 0xE5C01001, 0xEAFFFFFB, 0x04000300)

def crc16(data, crc=0xFFFF):
    for b in data:
        crc ^= b
        for _ in range(8): crc = (crc >> 1) ^ 0xA001 if crc & 1 else crc >> 1
    return crc

def rom(name, mode, level, ramp=300, maxl=10, cpu=0):
    a9 = bytearray(arm9)
    struct.pack_into("<5I", a9, 8, mode, level, ramp, maxl, cpu)
    a9 += b"\0" * (-len(a9) % 0x200)
    a9off = 0x8000; a7off = a9off + len(a9)
    body = bytearray(0x8000) + a9 + arm7
    body += b"\0" * (-len(body) % 0x200)
    h = bytearray(0x200)
    h[0:12] = b"DSSTRESS".ljust(12, b"\0"); h[12:16] = b"STRS"; h[16:18] = b"00"
    h[0x14] = 0                                              # 128 KB
    struct.pack_into("<8I", h, 0x20, a9off, 0x02000000, 0x02000000, len(a9),
                     a7off, 0x02380000, 0x02380000, len(arm7))
    struct.pack_into("<2I", h, 0x60, 0x00586000, 0x001808F8)
    struct.pack_into("<2I", h, 0x80, len(body), 0x200)
    struct.pack_into("<H", h, 0x15E, crc16(h[:0x15E]))
    body[0:0x200] = h
    body += b"\xff" * (0x20000 - len(body)) if len(body) < 0x20000 else b""
    with open(os.path.join(OUT, name), "wb") as f: f.write(body)
    return name

names = [rom("dsstress-ramp.nds", 1, 1)]
names += [rom(f"dsstress-L{l}.nds", 0, l) for l in range(1, 11)]
names += [rom("dsswap.nds", 2, 1, ramp=120)]            # screen swap (POWCNT1 bit 15) every 2 s, like DQ4's battles
print("arm9 %d bytes ->" % len(arm9), " ".join(names))
