#!/usr/bin/env python3
"""gen-color-shaders.py: writes shaders/ds-crisp-color.frag and ds-grid-color.frag from ds-crisp.frag and
ds-grid.frag by adding the NDS screen colour (edit the base shaders, then run this).

The colour profile is the one ROCKNIX's lcd1x+nds-color uses: linearise with gamma 1.91, 0.89 luminance, a 3x3
channel mix, back to gamma 1.91 (with a clamp before the last step: pow of a negative is undefined in GLSL and on
this GPU it bled red into saturated blues).

Speed (plan-1.4 section 6, measured 2026-09-28 with tools/shaders.sh, 800 MHz): written with pow() in highp the
colour cost ~0.9 ms per 640x480 panel on top of ds-crisp's 0.7. The GPU is limited by fp32 arithmetic there, not by
pow (a highp polynomial version took the same time); fp16 doubles the arithmetic rate. So the colour runs in mediump
with both gamma curves as polynomials: x^1.91 * 0.89 as a degree-4 polynomial and y^(1/1.91) as a degree-6
polynomial in sqrt(y) (near-minimax fits on Chebyshev nodes). ds-crisp-color 1.65 -> 1.31 ms per panel. It is not
bit-identical to the pow() version: on real frames up to 20% of pixels differ by 1 level of 255 and 0.007% by 2
(over all 16.7M colours, fp64: max 3 levels in the darkest colours, 5% off by 1). The texture coordinates stay highp
(they must: see ds-crisp.frag).
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
SH = os.path.join(HERE, "..", "shaders")

P1 = [-0.000192440297, 0.0161565261, 0.980162582, -0.15107093, 0.0450218219]                       # x^1.91 * 0.89
P2 = [-0.000458519754, 0.855903541, 0.564332005, -1.321717, 1.87310197, -1.36815007, 0.397060658]  # t^(2/1.91), t = sqrt(y)


def horner(coeffs, var):
    e = f"{coeffs[-1]:.9g}"
    for c in coeffs[-2::-1]:
        e = f"({e}) * {var} + {c:.9g}"
    return e


NDS_COLOR = f"""// NDS screen colour: the DS LCD's washed-out, channel-mixed look. The same profile ROCKNIX's lcd1x+nds-color
// uses: linearise with gamma 1.91, 0.89 luminance, a 3x3 channel mix, back to gamma 1.91. mediump, with both
// curves as polynomials (x^1.91 * 0.89, and y^(1/1.91) in sqrt(y)): ~2x faster than pow() in highp, within 1 level
// of it on 99.99% of pixels. Generated by tools/gen-color-shaders.py.
mediump vec3 ndsColor(mediump vec3 c)
{{
    mediump vec3 lin = clamp({horner(P1, 'c')}, 0.0, 1.0);
    lin = mat3( 0.87,  0.10,  0.10,
                0.255, 0.645, 0.17,
               -0.125, 0.255, 0.73) * lin;
    mediump vec3 t = sqrt(clamp(lin, 0.0, 1.0));
    return {horner(P2, 't')};
}}

"""


def make(base):
    src = open(os.path.join(SH, base + ".frag")).read()
    head = (f"// {base} + NDS screen colour (generated from {base}.frag by tools/gen-color-shaders.py: edit {base}.frag, "
            "then run it).\n")
    anchor = "uniform vec2 u_output_size;\n"
    assert anchor in src, base
    src = src.replace(anchor, anchor + "\n" + NDS_COLOR, 1)
    fetch = re.search(r"^(\s*)vec4 c = SWIZ\(texture2D\(.*\);\n", src, re.M)
    if fetch:                                   # the shader keeps the texel in c: correct it right after the fetch
        src = src[:fetch.end()] + f"{fetch.group(1)}c.rgb = ndsColor(c.rgb);\n" + src[fetch.end():]
    else:                                       # it writes the fetch straight out
        m = re.search(r"^(\s*)gl_FragColor = (SWIZ\(texture2D\(.*\));\n", src, re.M)
        assert m, base
        src = (src[:m.start()] + f"{m.group(1)}vec4 c = {m.group(2)};\n{m.group(1)}gl_FragColor = vec4(ndsColor(c.rgb), c.a);\n"
               + src[m.end():])
    with open(os.path.join(SH, base + "-color.frag"), "w") as f:
        f.write(head + src)
    print("wrote", base + "-color.frag")


if __name__ == "__main__":
    for b in ("ds-crisp", "ds-grid"):
        make(b)
